#include <stdafx.h>
#include "kernel.h"


// Non-critical stub functions

// Crt
DECLARE_STUB_FUNCTION_VOID(refii::kernel::_snwprintf_x, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::_swprintf_x, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::_vscwprintf_x, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::_vsnprintf_x, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::_vswprintf_x, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::sprintf_x, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::CertMonitorData, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::DbgBreakPoint, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::DebugMonitorData, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::vsprintf_x, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::DbgPrint, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::__C_specific_handler_x, ())

// Ex*
DECLARE_STUB_FUNCTION_VOID(refii::kernel::ExAllocatePoolTypeWithTag, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::ExFreePool, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::ExLoadedCommandLine, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::ExRegisterTitleTerminateNotification, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::ExTerminateThread, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::ExThreadObjectType, ())

// Ke*
DECLARE_STUB_FUNCTION_VOID(refii::kernel::KeEnableFpuExceptions, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::KeEnterCriticalRegion, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::KeLeaveCriticalRegion, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::KeLockL2, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::KeQueryBasePriorityThread, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::KeUnlockL2, ())

// Mm*
DECLARE_STUB_FUNCTION_VOID(refii::kernel::MmQueryAllocationSize, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::MmQueryStatistics, ())

// NetDll_*
DECLARE_STUB_FUNCTION_VOID(refii::kernel::NetDll_WSAStartup, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::NetDll_WSACleanup, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::NetDll_socket, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::NetDll_closesocket, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::NetDll_setsockopt, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::NetDll_bind, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::NetDll_connect, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::NetDll_listen, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::NetDll_accept, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::NetDll_select, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::NetDll_recv, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::NetDll_send, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::NetDll_inet_addr, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::NetDll___WSAFDIsSet, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::NetDll_XNetStartup, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::NetDll_XNetGetTitleXnAddr, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::NetDll_recvfrom, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::NetDll_sendto, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::NetDll_WSAGetLastError, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::NetDll_WSAGetOverlappedResult, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::NetDll_WSARecvFrom, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::NetDll_WSASendTo, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::NetDll_ioctlsocket, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::NetDll_XNetCleanup, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::NetDll_XNetConnect, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::NetDll_XNetGetConnectStatus, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::NetDll_XNetInAddrToXnAddr, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::NetDll_XNetQosListen, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::NetDll_XNetQosRelease, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::NetDll_XNetRandom, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::NetDll_XNetRegisterKey, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::NetDll_XNetUnregisterInAddr, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::NetDll_XNetUnregisterKey, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::NetDll_XNetXnAddrToInAddr, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::NetDll_XNetXnAddrToMachineId, ())

//Rtl*
DECLARE_STUB_FUNCTION_VOID(refii::kernel::RtlCaptureContext_x, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::RtlCompareStringN, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::RtlFreeAnsiString, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::RtlInitUnicodeString, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::RtlTimeToTimeFields, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::RtlUnicodeStringToAnsiString, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::RtlUnwind_x, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::RtlUpcaseUnicodeChar, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::RtlCompareMemoryUlong, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::RtlFillMemoryUlong, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::RtlNtStatusToDosError, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::RtlRaiseException_x, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::RtlImageXexHeaderField, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::RtlTimeFieldsToTime, ())

// Ob*
DECLARE_STUB_FUNCTION_VOID(refii::kernel::ObOpenObjectByName, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::ObReferenceObjectByName, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::ObIsTitleObject, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::ObReferenceObject, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::ObDereferenceObject, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::ObCreateSymbolicLink, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::ObDeleteSymbolicLink, ())

// Nt*
DECLARE_STUB_FUNCTION_RETURN(uint32_t, refii::kernel::NtFreeVirtualMemory, (), 0)
DECLARE_STUB_FUNCTION_RETURN(uint32_t, refii::kernel::NtCreateFile, (), 0)
DECLARE_STUB_FUNCTION_RETURN(uint32_t, refii::kernel::NtAllocateVirtualMemory, (), 0)
DECLARE_STUB_FUNCTION_VOID(refii::kernel::NtDeviceIoControlFile, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::NtFlushBuffersFile, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::NtQueryFullAttributesFile, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::NtWaitForMultipleObjectsEx, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::NtDuplicateObject, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::NtOpenFile, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::NtQueryDirectoryFile, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::NtQueryInformationFile, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::NtQueryVirtualMemory, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::NtQueryVolumeInformationFile, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::NtReadFile, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::NtReadFileScatter, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::NtSetInformationFile, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::NtWriteFile, ())
DECLARE_STUB_FUNCTION_RETURN(uint32_t, refii::kernel::NtQueueApcThread, (), 0)
DECLARE_STUB_FUNCTION_RETURN(uint32_t, refii::kernel::NtProtectVirtualMemory, (), 0)
DECLARE_STUB_FUNCTION_VOID(refii::kernel::NtCancelTimer, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::NtCreateTimer, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::NtSetTimerEx, ())

// X*
DECLARE_STUB_FUNCTION_VOID(refii::kernel::XeCryptBnQwBeSigVerify, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::XeCryptRotSumSha, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::XeCryptSha, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::XeCryptShaInit, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::XeCryptShaUpdate, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::XeCryptShaFinal, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::XeKeysConsolePrivateKeySign, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::XeKeysConsoleSignatureVerification, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::XeKeysGetKey, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::XMsgStartIORequestEx, ())
DECLARE_STUB_FUNCTION_RETURN(uint32_t, refii::kernel::XamShowMarketplaceUI, (), 0)
DECLARE_STUB_FUNCTION_RETURN(uint32_t, refii::kernel::XamUserCheckPrivilege, (), 0)
DECLARE_STUB_FUNCTION_RETURN(uint32_t, refii::kernel::XamUserAreUsersFriends, (), 0) // :(
DECLARE_STUB_FUNCTION_RETURN(uint32_t, refii::kernel::XamReadTileToTexture, (), 0)
DECLARE_STUB_FUNCTION_RETURN(uint32_t, refii::kernel::XamShowGamerCardUIForXUID, (), 0)
DECLARE_STUB_FUNCTION_RETURN(uint32_t, refii::kernel::XamContentGetLicenseMask, (), 0)
DECLARE_STUB_FUNCTION_RETURN(uint32_t, refii::kernel::XamParseGamerTileKey, (), 0)
DECLARE_STUB_FUNCTION_VOID(refii::kernel::XNotifyPositionUI, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::XAudioGetVoiceCategoryVolume, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::XNetLogonGetTitleID, ())
DECLARE_STUB_FUNCTION_RETURN(uint32_t, refii::kernel::XexLoadImage, (), 0)
DECLARE_STUB_FUNCTION_RETURN(uint32_t, refii::kernel::XexUnloadImage, (), 0)
DECLARE_STUB_FUNCTION_VOID(refii::kernel::XexGetProcedureAddress, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::XexGetModuleSection, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::XexLoadImageHeaders, ())
DECLARE_STUB_FUNCTION_VOID(refii::kernel::XexGetModuleHandle, ())
